spring.application.name=crud
server.port=8081
logging.level.org.springframework.amqp=DEBUG
logging.level.ortolan.empresa.crud.config=DEBUG
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.listener.simple.auto-startup=true

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/ticketflow?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
